### ISSUE TITLE
[ERROR] error reading * zip file is empty

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/jenkins-slave#14]
during mass jobs start each thread could corrupt downloading dependencies.
As result we see that tests could fail later due to the class not found exception.
also during compilation maven shows below error in spite of the fact that "-U" arg is provided:
[ERROR] error reading /root/.m2/repository/com/itextpdf/itextpdf/5.0.6/itextpdf-5.0.6.jar; zip file is empty

**Comment by vdelendik** [comment]
let's prepare jenkins-slave with already cloned and installed artifacts for
carina
carina-demo

it should guarantee we have 99% of dependencies prepopulated.

**Comment by vdelendik** [comment]
@okamara issue is fixed, new "qaprosoft/jenkins-slave:latest-alpine" pushed to hub docker.
to test you could do clear and start from latest 5.0-betaX qps-infra.

when you start 1st job, there shouldn't be a lot of downloading operations as all dependencies for carina and carina-demo are available inside jenkins-slave maven repo

**Comment by okamara** [comment]
Fixed.
