### ISSUE TITLE
unable to connect to 2.234 jenkins-master due to the outdated swarm.jar

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/jenkins-slave#16]
need upgrade swarm.jar from 3.6 to latest available 3.19 to solve all inconsistencies in connecting to latest jenkins

**Comment by vdelendik** [comment]
latest-alpine pushed to the hub docker
https://github.com/qaprosoft/jenkins-slave/commit/127e474c6c2d13cc22e77630b992a18531dd0d6e

successfully testsed on demo.qaprosoft.com with 
qaprosoft/jenkins-master:5.0-beta9

**Comment by okamara** [comment]
@vdelendik could you please add steps or details how I can check this issue

**Comment by okamara** [comment]
qaprosoft/jenkins-master:5.0-beta9 updated on local env.
