### ISSUE TITLE
integrate aws cli into the default alpine slave

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/jenkins-slave#17]
as we are going to move onto the open source a lot of static code analysis we have to provide default slave with ability to run aws cli to download jacoco binary report from aws s3

**Comment by vdelendik** [comment]
test scenario:
after clear.sh and start qps-infra from scratch (develop branch)

docker exec -ti jenkins-slave /bin/bash
aws
-> in output you should see:
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: the following arguments are required: command

**Comment by okamara** [comment]
Fixed.
