### ISSUE TITLE
remove carina and carina-demo source after populating maven dependencies

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/jenkins-slave#18]
1. no need to keep carina and carina-demo sources after building image
2. let's skip tests execution when compiling all sources

**Comment by vdelendik** [comment]
test scenario:
after clear.sh and start qps-infra from scratch (develop branch)
1) docker exec -ti jenkins-slave /bin/bash
2) ls -la /opt/
-> carina and carina-demo folders shouldn't be present

**Comment by okamara** [comment]
Fixed.
