### ISSUE TITLE
install lsof utility for all slaves (ubuntu and alpine)

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/jenkins-slave#23]
add valid install command for lsof utility for
Dockerfile
Dockerfile-alpine
Dockerfile-alpine-jdk11

**Comment by ilya-varchenya** [comment]
https://github.com/qaprosoft/jenkins-slave/pull/24

**Comment by ilya-varchenya** [comment]
@okamara ask me for a help for test this issue

**Comment by vdelendik** [comment]
we have to release updated slaves to hub docker

**Comment by vdelendik** [comment]
released new slaves:
latest
latest-alpine
latest-alpine-jdk11

Ideal testing scenario:
1) remove existing images on your host for jenkins-slave:latest-alpine
docker images
docker rmi <image_id>
2) change jenkins-slave tag version in.var to latest
3) start everything and verify "lsof" utility is available on the slave container:
docker exec -ti jenkins-slave /bin/bash
which lsof
-> path to the lsof utility should be displayed

repeat test for latest-alpine and latest-alpine-jdk11 slaves

**Comment by dhreben** [comment]
Verified
